// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {monitor} from '../models';
import {main} from '../models';

export function AddDevice(arg1:models.Device):Promise<void>;

export function CreateFirstAdminUser(arg1:string,arg2:string):Promise<void>;

export function CurrentUser():Promise<models.UserDTO>;

export function DeleteDevice(arg1:string):Promise<void>;

export function GetAuditLogs(arg1:number):Promise<Array<models.AuditLog>>;

export function GetStatusSnapshot():Promise<Record<string, monitor.DeviceState>>;

export function HasAnyUser():Promise<boolean>;

export function ImportDevices(arg1:Array<models.Device>):Promise<main.ImportResult>;

export function IsPolling():Promise<boolean>;

export function IsWindowVisible():Promise<boolean>;

export function ListDevices():Promise<Array<models.Device>>;

export function Login(arg1:string,arg2:string):Promise<models.UserDTO>;

export function Logout():Promise<void>;

export function MenuAbout():Promise<void>;

export function MenuAddIpDevice():Promise<void>;

export function MenuImportCSV():Promise<void>;

export function MenuOpenLogsFolder():Promise<void>;

export function MenuRefreshDevices():Promise<void>;

export function MenuShowAuditLog():Promise<void>;

export function MenuStartMonitoring():Promise<void>;

export function MenuStopMonitoring():Promise<void>;

export function QuitApp():Promise<void>;

export function SetPolling(arg1:boolean):Promise<void>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;
