// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1) {
  return window['go']['main']['App']['AddDevice'](arg1);
}

export function CreateFirstAdminUser(arg1, arg2) {
  return window['go']['main']['App']['CreateFirstAdminUser'](arg1, arg2);
}

export function CurrentUser() {
  return window['go']['main']['App']['CurrentUser']();
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function GetAuditLogs(arg1) {
  return window['go']['main']['App']['GetAuditLogs'](arg1);
}

export function GetStatusSnapshot() {
  return window['go']['main']['App']['GetStatusSnapshot']();
}

export function HasAnyUser() {
  return window['go']['main']['App']['HasAnyUser']();
}

export function ImportDevices(arg1) {
  return window['go']['main']['App']['ImportDevices'](arg1);
}

export function IsPolling() {
  return window['go']['main']['App']['IsPolling']();
}

export function IsWindowVisible() {
  return window['go']['main']['App']['IsWindowVisible']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MenuAbout() {
  return window['go']['main']['App']['MenuAbout']();
}

export function MenuAddIpDevice() {
  return window['go']['main']['App']['MenuAddIpDevice']();
}

export function MenuImportCSV() {
  return window['go']['main']['App']['MenuImportCSV']();
}

export function MenuOpenLogsFolder() {
  return window['go']['main']['App']['MenuOpenLogsFolder']();
}

export function MenuRefreshDevices() {
  return window['go']['main']['App']['MenuRefreshDevices']();
}

export function MenuShowAuditLog() {
  return window['go']['main']['App']['MenuShowAuditLog']();
}

export function MenuStartMonitoring() {
  return window['go']['main']['App']['MenuStartMonitoring']();
}

export function MenuStopMonitoring() {
  return window['go']['main']['App']['MenuStopMonitoring']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SetPolling(arg1) {
  return window['go']['main']['App']['SetPolling'](arg1);
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}
