// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {monitor} from '../models';
import {main} from '../models';

export function AddDevice(arg1:models.Device):Promise<void>;

export function DeleteDevice(arg1:string):Promise<void>;

export function GetStatusSnapshot():Promise<Record<string, monitor.DeviceState>>;

export function ImportDevices(arg1:Array<models.Device>):Promise<main.ImportResult>;

export function ListDevices():Promise<Array<models.Device>>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;
