// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1) {
  return window['go']['main']['App']['AddDevice'](arg1);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function GetStatusSnapshot() {
  return window['go']['main']['App']['GetStatusSnapshot']();
}

export function ImportDevices(arg1) {
  return window['go']['main']['App']['ImportDevices'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}
